### ISSUE TITLE
Publication ready tables

### ISSUE THREAD

**Issue by kristyrobledo** [ropensci/ozunconf19#8]
I'd like to put together some functions to manipulate outputs into publication ready tables. 

eg. 
"table 1"
- mean (SD) by group 
- median (Q1-Q3) option to have median (min-max) instead
- n (%)
(with the option to have a p-value as well)

also thinking 'logistic regression' table (n/N for each group, OR 95% CI, pvalue)
survival analysis table (event rates by group, Hazard ratio 95% CI, pvalue)
etc .....

Hopefully they will all be ready to go straight into a kable(). 
also thinking of a way to toggle these last two tables into create nice forestplots instead of a table.

**Comment by jenrichmond** [comment]
Hi Kristy
A bit like the tableone package?

https://cran.r-project.org/web/packages/tableone/vignettes/introduction.html

Jen

**Comment by kristyrobledo** [comment]
hahah yes - exactly! (seriously sometimes I just need to spend more time googling to find what I want before recreating the wheel)

OK so build on that I guess, with the other analysis tables.

**Comment by jenrichmond** [comment]
:) I only learned about this one a week ago! And not from googling !!

**Comment by kristyrobledo** [comment]
thinking out loud.... is there anyway to search all the R packages easily to find packages to do certain things??
eg each package has key words attached to it, and then you search to (easily) find what you want...

**Comment by ekothe** [comment]
I think you might also want to have a look at papaja for the tables https://github.com/crsh/papaja

**Comment by jenrichmond** [comment]
emily is the table queen! thanks for telling me about tableone!

**Comment by orchid00** [comment]
hi @kristyrobledo to your question 

> is the anyway to search all the R packages

- the answer is yes!

One option is METACRAN https://www.r-pkg.org/ it has a very specific search, the only drawback might be only searching on CRAN.
The other option is R Package Documentation https://rdrr.io/ - but it didn't return the packages that metacran found
Third option: https://www.rdocumentation.org

there might be many other options

**Comment by kristyrobledo** [comment]
seriously, sometimes its just about finding the right R package!!! 
Maybe we need an R package to help us find the right R package...... maybe pulling together the information from the above 3 sources?

**Comment by kristyrobledo** [comment]
> I think you might also want to have a look at papaja for the tables https://github.com/crsh/papaja

this is fantastic - thanks so much @ekothe! the wrapper apa_table() seems to be exactly what I was thinking :)

**Comment by njtierney** [comment]
This is indeed an interesting topic! There was a bit of a discussion around searching through R packages at a past unconf in the USA: https://github.com/ropensci/unconf17/issues/78

Which resulted in the package metrics package - https://github.com/ropenscilabs/packagemetrics

Which resulted in a table of packages that make tables :tada: :  https://github.com/ropenscilabs/packagemetrics#creating-a-pretty-metrics_table

Perhaps that can provide a good starting place for some discussion on creating tables?

In addition to what has been discussed, there is also the `janitor` package, by
@sfirke, which contains loads of really nice data cleaning shortcuts, and a really nice flexible approach to creating tables -  a`tabyl`. You can read more in this [tabyl vignette](https://sfirke.github.io/janitor/articles/tabyls.html), which has these really nice `adorn_` functions for adding extra columns.

**Comment by robjhyndman** [comment]
Very useful @njtierney! It is also worth looking at the [Reproducible Research](https://cran.r-project.org/web/views/ReproducibleResearch.html) task view which lists some table-making packages including some not on the "table of tables" you link to.

**Comment by orchid00** [comment]
@kristyrobledo what about this https://www.littlemissdata.com/blog/prettytables

**Comment by kristyrobledo** [comment]
We have burned this to the ground....

ApaTables and papaja kind of answered this question.
