### ISSUE TITLE
Validate Tabular Data

### ISSUE THREAD

**Issue by orchid00** [ropensci/ozunconf19#9]
I think there might be something out there, but at least I'll find out!

"goodtables is a free, open-source, hosted service for validating tabular data. goodtables checks your data for its structure, and, optionally, its adherence to a specified schema."
Ref: https://frictionlessdata.io/docs/validating-data/

The idea emerged out of this: https://github.com/frictionlessdata/goodtables-py
"Using the Python goodtables library. This allows you full control over the validation process but requires knowledge of Python."

It would be cool to kind of translate that into a **goodtables-R**

The closest package I found is https://github.com/data-cleaning/validate
but it is not really checking structure like goodtables. 

Someone interested to look into this?

**Comment by orchid00** [comment]
Also related visdat from Nick Tierney http://visdat.njtierney.com/

**Comment by stefaniebutland** [comment]
@bzkrouse @wlandau "validation" made me think of pharma industry. Are you aware of any tools? 👆🏼

**Comment by wlandau** [comment]
Broadly speaking, there's the R Validation Hub: https://www.pharmar.org/. It was discussed at the R/Pharma conference this year.

**Comment by wlandau** [comment]
As for specific tools, the whole process of TFL-generation is still so SAS-based that I do not have specific recommendations about tools in R.

**Comment by bzkrouse** [comment]
Thanks for looping us in @stefaniebutland !

I'm not sure if this is exactly what you're after, but a nice tool for comparing 2 datasets is the [comparedf](https://cran.r-project.org/web/packages/arsenal/vignettes/comparedf.html) function from arsenal package.

This previous unconf [thread](https://github.com/ropensci/unconf15/issues/19) also came to mind (I remembered it from some previous research I had done).
